### ISSUE TITLE
upgrade:tests references nonexistent class

### ISSUE THREAD

**Issue by lfolco** [magento/magento2-functional-testing-framework#900]
### Preconditions

1. Be on v4.2.1

### Steps to reproduce

1. Run `vendor/bin/mftf upgrade:tests`

### Expected result

Tests get upgrade

### Actual result

Fatal error:

```
Fatal error: Uncaught Error: Class "Magento\FunctionalTestingFramework\StaticCheck\ActionGroupArgumentsCheck" not found in /Users/lfolco/Sites/myproject/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/Upgrade/RemoveUnusedArguments.php:43
Stack trace:
#0 /Users/lfolco/Sites/myproject/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/Console/UpgradeTestsCommand.php(60): Magento\FunctionalTestingFramework\Upgrade\RemoveUnusedArguments->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /Users/lfolco/Sites/myproject/vendor/symfony/console/Command/Command.php(298): Magento\FunctionalTestingFramework\Console\UpgradeTestsCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/lfolco/Sites/myproject/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/lfolco/Sites/myproject/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Magento\FunctionalTestingFramework\Console\UpgradeTestsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/lfolco/Sites/myproject/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/lfolco/Sites/myproject/vendor/magento/magento2-functional-testing-framework/bin/mftf(40): Symfony\Component\Console\Application->run()
#6 /Users/lfolco/Sites/myproject/vendor/bin/mftf(117): include('/Users/lfolco/S...')
#7 {main}
  thrown in /Users/lfolco/Sites/myproject/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/Upgrade/RemoveUnusedArguments.php on line 43
```

**Comment by nborgawkar** [comment]
Is there any update on this? Facing same issue while executing `sudo vendor/bin/mftf build:project --upgrade` command
